# -*- coding: utf-8 -*-
"""DocumentSimilarity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lRacfryyheHVGePC2WYPiw7pkfJoJHAI
"""

from langchain_huggingface import HuggingFaceEmbeddings


from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")

documents = [
    "Virat Kohli is an Indian cricketer who currently captains the India national team. A right-handed top-order batsman, Kohli is regarded as one of the best batsmen in the world",
    "MS Dhoni is a former Indian Cricket Captain famous for his calm demeanor and finishing skills",
    "Sachin Tendulkar, also known as the 'God of Cricket', holds many batting records",
    "Rohit Sharma is known for his elegant batting and record breaking double centuries",
    "Jasprit Bumrah is an Indian Fast bowler known for his unorthodox action and yorkers"
]

query = 'who the fuck is virat koli'

doc_embeds = embeddings.embed_documents(documents)
query_embed = embeddings.embed_query(query)

similarity_scores = cosine_similarity([query_embed], doc_embeds)[0] # always give 2D vector
print(similarity_scores)
# sorted_scores = sorted(list(enumerate(similarity_scores)), key = lambda x: x[1])

# doc_index = sorted_scores[-1][0]

# result_Doc = documents[doc_index]

# print(result_Doc)